library(dplyr)
library(tidyr)
library(purrr)
library(glue)

source("data-raw/wrapper_mapping.R", local = TRUE)

# Generated file naming convention
GENERATED_FILE_PREFIX <- "z_generated_"

# Build the file path for a generated wrapper file
build_file_path <- function(logger) {
    paste0("R/", GENERATED_FILE_PREFIX, logger, ".R")
}

# Clean up old generated files before creating new ones
old_generated_files <- list.files("R", pattern = paste0("^", GENERATED_FILE_PREFIX, ".*\\.R$"), full.names = TRUE)
if (length(old_generated_files) > 0) {
    file.remove(old_generated_files)
    message("Removed ", length(old_generated_files), " old generated file(s)")
}

# Shared roxygen documentation template
generate_roxygen_header <- function(pkg, fn) {
    pkg_version <- as.character(packageVersion(pkg))
    
    glue("
#' Wrapper around {pkg}::{fn} that prints information about the operation
#'
#' @description
#' Wrapper around [{pkg}::{fn}()] that prints information about the operation.
#'
#' @details
#' Documentation generated from {pkg} version {pkg_version}.
#'
#' @inheritParams {pkg}::{fn}
#' @inheritDotParams {pkg}::{fn}
#'
#' @return See [{pkg}::{fn}()]
#' @seealso [{pkg}::{fn}()]
#' @export", .trim = FALSE)
}

# Generate wrapper for regular functions: function(.data, ...)
generate_regular_wrapper <- function(full_fn_name, logger_name) {
    parts <- parse_function_name(full_fn_name)
    
    # Get first argument name from original function
    orig_fn <- getExportedValue(parts$pkg, parts$fn)
    first_arg <- names(formals(orig_fn))[1]
    
    roxygen <- generate_roxygen_header(parts$pkg, parts$fn)
    
    glue("
{roxygen}
{parts$fn} <- function({first_arg}, ...) {{
\tresult <- {parts$pkg}::{parts$fn}({first_arg}, ...)
\t{logger_name}({first_arg}, result, \"{parts$fn}\", ...)
\tresult
}}
", .trim = FALSE)
}

# Generate wrapper for join functions: function(x, y, by = NULL, ...)
generate_join_wrapper <- function(full_fn_name, logger_name) {
    parts <- parse_function_name(full_fn_name)
    
    roxygen <- generate_roxygen_header(parts$pkg, parts$fn)
    
    glue("
{roxygen}
{parts$fn} <- function(x, y, by = NULL, ...) {{
\tresult <- {parts$pkg}::{parts$fn}(x, y, by = by, ...)
\t{logger_name}(x, y, by, result, \"{parts$fn}\", 
\t              .name_x = deparse1(substitute(x)), 
\t              .name_y = deparse1(substitute(y)), ...)
\tresult
}}
", .trim = FALSE)
}

# Save to disk
header_base <- "# Generated by data-raw/generate_wrappers.R: do not edit by hand\n"

# Map of logger names to global variable declarations
globals_map <- list(
    log_longer_wider = "\nutils::globalVariables(c('name', 'value'))\n"
)

# Helper function to generate and write wrapper files
generate_and_write <- function(wrappers, generator) {
    iwalk(wrappers, function(fns, logger) {
        file_path <- build_file_path(logger)
        
        code_blocks <- map_chr(fns, ~generator(.x, logger))
        
        # Add global variables if defined for this logger
        globals <- globals_map[[logger]] %||% ""
        
        writeLines(
            c(header_base, "# Logger category: ", logger, "\n",
              code_blocks,
              globals),
            file_path
        )
        message("Generated: ", file_path)
    })
}

# Generate all wrappers
generate_and_write(regular_wrappers, generate_regular_wrapper)
generate_and_write(join_wrappers, generate_join_wrapper)

# Update documentation
devtools::document()
