# Generated by data-raw/generate_wrappers.R: do not edit by hand
# Generated at: 2026-02-07 16:02:39.276079



#' Wrapper around dplyr::filter that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::filter()] that prints information about the operation.
#'
#' @inherit dplyr::filter return
#' @inheritParams dplyr::filter
#'
#'
#' @seealso [dplyr::filter()]
#'
#' @export
filter <- function(.data, ..., .by = NULL, .preserve = FALSE) {
	.call <- match.call(definition = dplyr::filter, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::filter)
	.call$.funname <- 'filter'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::filter_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::filter_all()] that prints information about the operation.
#'
#' @inherit dplyr::filter_all return
#' @inheritParams dplyr::filter_all
#'
#'
#' @seealso [dplyr::filter_all()]
#'
#' @export
filter_all <- function(.tbl, .vars_predicate, .preserve = FALSE) {
	.call <- match.call(definition = dplyr::filter_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::filter_all)
	.call$.funname <- 'filter_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::filter_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::filter_if()] that prints information about the operation.
#'
#' @inherit dplyr::filter_if return
#' @inheritParams dplyr::filter_if
#'
#'
#' @seealso [dplyr::filter_if()]
#'
#' @export
filter_if <- function(.tbl, .predicate, .vars_predicate, .preserve = FALSE) {
	.call <- match.call(definition = dplyr::filter_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::filter_if)
	.call$.funname <- 'filter_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::filter_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::filter_at()] that prints information about the operation.
#'
#' @inherit dplyr::filter_at return
#' @inheritParams dplyr::filter_at
#'
#'
#' @seealso [dplyr::filter_at()]
#'
#' @export
filter_at <- function(.tbl, .vars, .vars_predicate, .preserve = FALSE) {
	.call <- match.call(definition = dplyr::filter_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::filter_at)
	.call$.funname <- 'filter_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::distinct that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::distinct()] that prints information about the operation.
#'
#' @inherit dplyr::distinct return
#' @inheritParams dplyr::distinct
#'
#'
#' @seealso [dplyr::distinct()]
#'
#' @export
distinct <- function(.data, ..., .keep_all = FALSE) {
	.call <- match.call(definition = dplyr::distinct, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::distinct)
	.call$.funname <- 'distinct'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::distinct_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::distinct_all()] that prints information about the operation.
#'
#' @inherit dplyr::distinct_all return
#' @inheritParams dplyr::distinct_all
#'
#'
#' @seealso [dplyr::distinct_all()]
#'
#' @export
distinct_all <- function(.tbl, .funs = list(), ..., .keep_all = FALSE) {
	.call <- match.call(definition = dplyr::distinct_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::distinct_all)
	.call$.funname <- 'distinct_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::distinct_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::distinct_if()] that prints information about the operation.
#'
#' @inherit dplyr::distinct_if return
#' @inheritParams dplyr::distinct_if
#'
#'
#' @seealso [dplyr::distinct_if()]
#'
#' @export
distinct_if <- function(.tbl, .predicate, .funs = list(), ..., .keep_all = FALSE) {
	.call <- match.call(definition = dplyr::distinct_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::distinct_if)
	.call$.funname <- 'distinct_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::distinct_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::distinct_at()] that prints information about the operation.
#'
#' @inherit dplyr::distinct_at return
#' @inheritParams dplyr::distinct_at
#'
#'
#' @seealso [dplyr::distinct_at()]
#'
#' @export
distinct_at <- function(.tbl, .vars, .funs = list(), ..., .keep_all = FALSE) {
	.call <- match.call(definition = dplyr::distinct_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::distinct_at)
	.call$.funname <- 'distinct_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::top_n that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::top_n()] that prints information about the operation.
#'
#' @inherit dplyr::top_n return
#' @inheritParams dplyr::top_n
#'
#'
#' @seealso [dplyr::top_n()]
#'
#' @export
top_n <- function(x, n, wt) {
	.call <- match.call(definition = dplyr::top_n, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::top_n)
	.call$.funname <- 'top_n'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::top_frac that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::top_frac()] that prints information about the operation.
#'
#' @inherit dplyr::top_frac return
#' @inheritParams dplyr::top_frac
#'
#'
#' @seealso [dplyr::top_frac()]
#'
#' @export
top_frac <- function(x, n, wt) {
	.call <- match.call(definition = dplyr::top_frac, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::top_frac)
	.call$.funname <- 'top_frac'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::sample_n that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::sample_n()] that prints information about the operation.
#'
#' @inherit dplyr::sample_n return
#' @inheritParams dplyr::sample_n
#'
#'
#' @seealso [dplyr::sample_n()]
#'
#' @export
sample_n <- function(tbl, size, replace = FALSE, weight = NULL, .env = NULL, ...) {
	.call <- match.call(definition = dplyr::sample_n, expand.dots = TRUE)
	names(.call)[names(.call) == 'tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::sample_n)
	.call$.funname <- 'sample_n'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::sample_frac that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::sample_frac()] that prints information about the operation.
#'
#' @inherit dplyr::sample_frac return
#' @inheritParams dplyr::sample_frac
#'
#'
#' @seealso [dplyr::sample_frac()]
#'
#' @export
sample_frac <- function(tbl, size = 1, replace = FALSE, weight = NULL, .env = NULL, ...) {
	.call <- match.call(definition = dplyr::sample_frac, expand.dots = TRUE)
	names(.call)[names(.call) == 'tbl'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::sample_frac)
	.call$.funname <- 'sample_frac'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::slice that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::slice()] that prints information about the operation.
#'
#' @inherit dplyr::slice return
#' @inheritParams dplyr::slice
#'
#'
#' @seealso [dplyr::slice()]
#'
#' @export
slice <- function(.data, ..., .by = NULL, .preserve = FALSE) {
	.call <- match.call(definition = dplyr::slice, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::slice)
	.call$.funname <- 'slice'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::slice_head that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::slice_head()] that prints information about the operation.
#'
#' @inherit dplyr::slice_head return
#' @inheritParams dplyr::slice_head
#'
#'
#' @seealso [dplyr::slice_head()]
#'
#' @export
slice_head <- function(.data, ..., n, prop, by = NULL) {
	.call <- match.call(definition = dplyr::slice_head, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::slice_head)
	.call$.funname <- 'slice_head'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::slice_tail that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::slice_tail()] that prints information about the operation.
#'
#' @inherit dplyr::slice_tail return
#' @inheritParams dplyr::slice_tail
#'
#'
#' @seealso [dplyr::slice_tail()]
#'
#' @export
slice_tail <- function(.data, ..., n, prop, by = NULL) {
	.call <- match.call(definition = dplyr::slice_tail, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::slice_tail)
	.call$.funname <- 'slice_tail'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::slice_min that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::slice_min()] that prints information about the operation.
#'
#' @inherit dplyr::slice_min return
#' @inheritParams dplyr::slice_min
#'
#'
#' @seealso [dplyr::slice_min()]
#'
#' @export
slice_min <- function(.data, order_by, ..., n, prop, by = NULL, with_ties = TRUE, na_rm = FALSE) {
	.call <- match.call(definition = dplyr::slice_min, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::slice_min)
	.call$.funname <- 'slice_min'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::slice_max that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::slice_max()] that prints information about the operation.
#'
#' @inherit dplyr::slice_max return
#' @inheritParams dplyr::slice_max
#'
#'
#' @seealso [dplyr::slice_max()]
#'
#' @export
slice_max <- function(.data, order_by, ..., n, prop, by = NULL, with_ties = TRUE, na_rm = FALSE) {
	.call <- match.call(definition = dplyr::slice_max, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::slice_max)
	.call$.funname <- 'slice_max'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::slice_sample that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::slice_sample()] that prints information about the operation.
#'
#' @inherit dplyr::slice_sample return
#' @inheritParams dplyr::slice_sample
#'
#'
#' @seealso [dplyr::slice_sample()]
#'
#' @export
slice_sample <- function(.data, ..., n, prop, by = NULL, weight_by = NULL, replace = FALSE) {
	.call <- match.call(definition = dplyr::slice_sample, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(dplyr::slice_sample)
	.call$.funname <- 'slice_sample'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::drop_na that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::drop_na()] that prints information about the operation.
#'
#' @inherit tidyr::drop_na return
#' @inheritParams tidyr::drop_na
#'
#'
#' @seealso [tidyr::drop_na()]
#'
#' @export
drop_na <- function(data, ...) {
	.call <- match.call(definition = tidyr::drop_na, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_filter
	.call$.fun <- quote(tidyr::drop_na)
	.call$.funname <- 'drop_na'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::inner_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::inner_join()] that prints information about the operation.
#'
#' @inherit dplyr::inner_join return
#' @inheritParams dplyr::inner_join
#'
#'
#' @seealso [dplyr::inner_join()]
#'
#' @export
inner_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::inner_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::inner_join)
	.call$.funname <- 'inner_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::full_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::full_join()] that prints information about the operation.
#'
#' @inherit dplyr::full_join return
#' @inheritParams dplyr::full_join
#'
#'
#' @seealso [dplyr::full_join()]
#'
#' @export
full_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::full_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::full_join)
	.call$.funname <- 'full_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::left_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::left_join()] that prints information about the operation.
#'
#' @inherit dplyr::left_join return
#' @inheritParams dplyr::left_join
#'
#'
#' @seealso [dplyr::left_join()]
#'
#' @export
left_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::left_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::left_join)
	.call$.funname <- 'left_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::right_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::right_join()] that prints information about the operation.
#'
#' @inherit dplyr::right_join return
#' @inheritParams dplyr::right_join
#'
#'
#' @seealso [dplyr::right_join()]
#'
#' @export
right_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::right_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::right_join)
	.call$.funname <- 'right_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::anti_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::anti_join()] that prints information about the operation.
#'
#' @inherit dplyr::anti_join return
#' @inheritParams dplyr::anti_join
#'
#'
#' @seealso [dplyr::anti_join()]
#'
#' @export
anti_join <- function(x, y, by = NULL, copy = FALSE, ...) {
	.call <- match.call(definition = dplyr::anti_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::anti_join)
	.call$.funname <- 'anti_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::semi_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::semi_join()] that prints information about the operation.
#'
#' @inherit dplyr::semi_join return
#' @inheritParams dplyr::semi_join
#'
#'
#' @seealso [dplyr::semi_join()]
#'
#' @export
semi_join <- function(x, y, by = NULL, copy = FALSE, ...) {
	.call <- match.call(definition = dplyr::semi_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::semi_join)
	.call$.funname <- 'semi_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate()] that prints information about the operation.
#'
#' @inherit dplyr::mutate return
#' @inheritParams dplyr::mutate
#'
#'
#' @seealso [dplyr::mutate()]
#'
#' @export
mutate <- function(.data, ...) {
	.call <- match.call(definition = dplyr::mutate, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate)
	.call$.funname <- 'mutate'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate_all()] that prints information about the operation.
#'
#' @inherit dplyr::mutate_all return
#' @inheritParams dplyr::mutate_all
#'
#'
#' @seealso [dplyr::mutate_all()]
#'
#' @export
mutate_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::mutate_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate_all)
	.call$.funname <- 'mutate_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate_if()] that prints information about the operation.
#'
#' @inherit dplyr::mutate_if return
#' @inheritParams dplyr::mutate_if
#'
#'
#' @seealso [dplyr::mutate_if()]
#'
#' @export
mutate_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::mutate_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate_if)
	.call$.funname <- 'mutate_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate_at()] that prints information about the operation.
#'
#' @inherit dplyr::mutate_at return
#' @inheritParams dplyr::mutate_at
#'
#'
#' @seealso [dplyr::mutate_at()]
#'
#' @export
mutate_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::mutate_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate_at)
	.call$.funname <- 'mutate_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute()] that prints information about the operation.
#'
#' @inherit dplyr::transmute return
#' @inheritParams dplyr::transmute
#'
#'
#' @seealso [dplyr::transmute()]
#'
#' @export
transmute <- function(.data, ...) {
	.call <- match.call(definition = dplyr::transmute, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute)
	.call$.funname <- 'transmute'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute_all()] that prints information about the operation.
#'
#' @inherit dplyr::transmute_all return
#' @inheritParams dplyr::transmute_all
#'
#'
#' @seealso [dplyr::transmute_all()]
#'
#' @export
transmute_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::transmute_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute_all)
	.call$.funname <- 'transmute_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute_if()] that prints information about the operation.
#'
#' @inherit dplyr::transmute_if return
#' @inheritParams dplyr::transmute_if
#'
#'
#' @seealso [dplyr::transmute_if()]
#'
#' @export
transmute_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::transmute_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute_if)
	.call$.funname <- 'transmute_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute_at()] that prints information about the operation.
#'
#' @inherit dplyr::transmute_at return
#' @inheritParams dplyr::transmute_at
#'
#'
#' @seealso [dplyr::transmute_at()]
#'
#' @export
transmute_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::transmute_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute_at)
	.call$.funname <- 'transmute_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::add_tally that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::add_tally()] that prints information about the operation.
#'
#' @inherit dplyr::add_tally return
#' @inheritParams dplyr::add_tally
#'
#'
#' @seealso [dplyr::add_tally()]
#'
#' @export
add_tally <- function(x, wt = NULL, sort = FALSE, name = NULL) {
	.call <- match.call(definition = dplyr::add_tally, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::add_tally)
	.call$.funname <- 'add_tally'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::add_count that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::add_count()] that prints information about the operation.
#'
#' @inherit dplyr::add_count return
#' @inheritParams dplyr::add_count
#' @importFrom lifecycle deprecated
#'
#' @seealso [dplyr::add_count()]
#'
#' @export
add_count <- function(x, ..., wt = NULL, sort = FALSE, name = NULL, .drop = deprecated()) {
	.call <- match.call(definition = dplyr::add_count, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::add_count)
	.call$.funname <- 'add_count'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::replace_na that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::replace_na()] that prints information about the operation.
#'
#' @inherit tidyr::replace_na return
#' @inheritParams tidyr::replace_na
#'
#'
#' @seealso [tidyr::replace_na()]
#'
#' @export
replace_na <- function(data, replace, ...) {
	.call <- match.call(definition = tidyr::replace_na, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(tidyr::replace_na)
	.call$.funname <- 'replace_na'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::fill that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::fill()] that prints information about the operation.
#'
#' @inherit tidyr::fill return
#' @inheritParams tidyr::fill
#'
#'
#' @seealso [tidyr::fill()]
#'
#' @export
fill <- function(data, ..., .by = NULL, .direction = c("down", "up", "downup", "updown")) {
	.call <- match.call(definition = tidyr::fill, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(tidyr::fill)
	.call$.funname <- 'fill'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select()] that prints information about the operation.
#'
#' @inherit dplyr::select return
#' @inheritParams dplyr::select
#'
#'
#' @seealso [dplyr::select()]
#'
#' @export
select <- function(.data, ...) {
	.call <- match.call(definition = dplyr::select, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select)
	.call$.funname <- 'select'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select_all()] that prints information about the operation.
#'
#' @inherit dplyr::select_all return
#' @inheritParams dplyr::select_all
#'
#'
#' @seealso [dplyr::select_all()]
#'
#' @export
select_all <- function(.tbl, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::select_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select_all)
	.call$.funname <- 'select_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select_if()] that prints information about the operation.
#'
#' @inherit dplyr::select_if return
#' @inheritParams dplyr::select_if
#'
#'
#' @seealso [dplyr::select_if()]
#'
#' @export
select_if <- function(.tbl, .predicate, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::select_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select_if)
	.call$.funname <- 'select_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select_at()] that prints information about the operation.
#'
#' @inherit dplyr::select_at return
#' @inheritParams dplyr::select_at
#'
#'
#' @seealso [dplyr::select_at()]
#'
#' @export
select_at <- function(.tbl, .vars, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::select_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select_at)
	.call$.funname <- 'select_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::relocate that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::relocate()] that prints information about the operation.
#'
#' @inherit dplyr::relocate return
#' @inheritParams dplyr::relocate
#'
#'
#' @seealso [dplyr::relocate()]
#'
#' @export
relocate <- function(.data, ..., .before = NULL, .after = NULL) {
	.call <- match.call(definition = dplyr::relocate, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::relocate)
	.call$.funname <- 'relocate'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize()] that prints information about the operation.
#'
#' @inherit dplyr::summarize return
#' @inheritParams dplyr::summarize
#'
#'
#' @seealso [dplyr::summarize()]
#'
#' @export
summarize <- function(.data, ..., .by = NULL, .groups = NULL) {
	.call <- match.call(definition = dplyr::summarize, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize)
	.call$.funname <- 'summarize'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize_all()] that prints information about the operation.
#'
#' @inherit dplyr::summarize_all return
#' @inheritParams dplyr::summarize_all
#'
#'
#' @seealso [dplyr::summarize_all()]
#'
#' @export
summarize_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::summarize_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize_all)
	.call$.funname <- 'summarize_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize_at()] that prints information about the operation.
#'
#' @inherit dplyr::summarize_at return
#' @inheritParams dplyr::summarize_at
#'
#'
#' @seealso [dplyr::summarize_at()]
#'
#' @export
summarize_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::summarize_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize_at)
	.call$.funname <- 'summarize_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize_if()] that prints information about the operation.
#'
#' @inherit dplyr::summarize_if return
#' @inheritParams dplyr::summarize_if
#'
#'
#' @seealso [dplyr::summarize_if()]
#'
#' @export
summarize_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::summarize_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize_if)
	.call$.funname <- 'summarize_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise()] that prints information about the operation.
#'
#' @inherit dplyr::summarise return
#' @inheritParams dplyr::summarise
#'
#'
#' @seealso [dplyr::summarise()]
#'
#' @export
summarise <- function(.data, ..., .by = NULL, .groups = NULL) {
	.call <- match.call(definition = dplyr::summarise, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise)
	.call$.funname <- 'summarise'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise_all()] that prints information about the operation.
#'
#' @inherit dplyr::summarise_all return
#' @inheritParams dplyr::summarise_all
#'
#'
#' @seealso [dplyr::summarise_all()]
#'
#' @export
summarise_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::summarise_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise_all)
	.call$.funname <- 'summarise_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise_at()] that prints information about the operation.
#'
#' @inherit dplyr::summarise_at return
#' @inheritParams dplyr::summarise_at
#'
#'
#' @seealso [dplyr::summarise_at()]
#'
#' @export
summarise_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::summarise_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise_at)
	.call$.funname <- 'summarise_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise_if()] that prints information about the operation.
#'
#' @inherit dplyr::summarise_if return
#' @inheritParams dplyr::summarise_if
#'
#'
#' @seealso [dplyr::summarise_if()]
#'
#' @export
summarise_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::summarise_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise_if)
	.call$.funname <- 'summarise_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::tally that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::tally()] that prints information about the operation.
#'
#' @inherit dplyr::tally return
#' @inheritParams dplyr::tally
#'
#'
#' @seealso [dplyr::tally()]
#'
#' @export
tally <- function(x, wt = NULL, sort = FALSE, name = NULL) {
	.call <- match.call(definition = dplyr::tally, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::tally)
	.call$.funname <- 'tally'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::count that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::count()] that prints information about the operation.
#'
#' @inherit dplyr::count return
#' @inheritParams dplyr::count
#'
#'
#' @seealso [dplyr::count()]
#'
#' @export
count <- function(x, ..., wt = NULL, sort = FALSE, name = NULL) {
	.call <- match.call(definition = dplyr::count, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::count)
	.call$.funname <- 'count'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::uncount that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::uncount()] that prints information about the operation.
#'
#' @inherit tidyr::uncount return
#' @inheritParams tidyr::uncount
#'
#'
#' @seealso [tidyr::uncount()]
#'
#' @export
uncount <- function(data, weights, ..., .remove = TRUE, .id = NULL) {
	.call <- match.call(definition = tidyr::uncount, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(tidyr::uncount)
	.call$.funname <- 'uncount'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by()] that prints information about the operation.
#'
#' @inherit dplyr::group_by return
#' @inheritParams dplyr::group_by
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by()]
#'
#' @export
group_by <- function(.data, ..., .add = FALSE, .drop = group_by_drop_default(.data)) {
	.call <- match.call(definition = dplyr::group_by, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by)
	.call$.funname <- 'group_by'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by_all()] that prints information about the operation.
#'
#' @inherit dplyr::group_by_all return
#' @inheritParams dplyr::group_by_all
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by_all()]
#'
#' @export
group_by_all <- function(.tbl, .funs = list(), ..., .add = FALSE, .drop = group_by_drop_default(.tbl)) {
	.call <- match.call(definition = dplyr::group_by_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by_all)
	.call$.funname <- 'group_by_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by_at()] that prints information about the operation.
#'
#' @inherit dplyr::group_by_at return
#' @inheritParams dplyr::group_by_at
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by_at()]
#'
#' @export
group_by_at <- function(.tbl, .vars, .funs = list(), ..., .add = FALSE, .drop = group_by_drop_default(.tbl)) {
	.call <- match.call(definition = dplyr::group_by_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by_at)
	.call$.funname <- 'group_by_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by_if()] that prints information about the operation.
#'
#' @inherit dplyr::group_by_if return
#' @inheritParams dplyr::group_by_if
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by_if()]
#'
#' @export
group_by_if <- function(.tbl, .predicate, .funs = list(), ..., .add = FALSE, .drop = group_by_drop_default(.tbl)) {
	.call <- match.call(definition = dplyr::group_by_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by_if)
	.call$.funname <- 'group_by_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::ungroup that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::ungroup()] that prints information about the operation.
#'
#' @inherit dplyr::ungroup return
#' @inheritParams dplyr::ungroup
#'
#'
#' @seealso [dplyr::ungroup()]
#'
#' @export
ungroup <- function(x, ...) {
	.call <- match.call(definition = dplyr::ungroup, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::ungroup)
	.call$.funname <- 'ungroup'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename()] that prints information about the operation.
#'
#' @inherit dplyr::rename return
#' @inheritParams dplyr::rename
#'
#'
#' @seealso [dplyr::rename()]
#'
#' @export
rename <- function(.data, ...) {
	.call <- match.call(definition = dplyr::rename, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename)
	.call$.funname <- 'rename'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_all()] that prints information about the operation.
#'
#' @inherit dplyr::rename_all return
#' @inheritParams dplyr::rename_all
#'
#'
#' @seealso [dplyr::rename_all()]
#'
#' @export
rename_all <- function(.tbl, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::rename_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_all)
	.call$.funname <- 'rename_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_if()] that prints information about the operation.
#'
#' @inherit dplyr::rename_if return
#' @inheritParams dplyr::rename_if
#'
#'
#' @seealso [dplyr::rename_if()]
#'
#' @export
rename_if <- function(.tbl, .predicate, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::rename_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_if)
	.call$.funname <- 'rename_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_at()] that prints information about the operation.
#'
#' @inherit dplyr::rename_at return
#' @inheritParams dplyr::rename_at
#'
#'
#' @seealso [dplyr::rename_at()]
#'
#' @export
rename_at <- function(.tbl, .vars, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::rename_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_at)
	.call$.funname <- 'rename_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_with that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_with()] that prints information about the operation.
#'
#' @inherit dplyr::rename_with return
#' @inheritParams dplyr::rename_with
#' @importFrom tidyselect everything
#'
#' @seealso [dplyr::rename_with()]
#'
#' @export
rename_with <- function(.data, .fn, .cols = everything(), ...) {
	.call <- match.call(definition = dplyr::rename_with, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_with)
	.call$.funname <- 'rename_with'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::pivot_longer that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::pivot_longer()] that prints information about the operation.
#'
#' @inherit tidyr::pivot_longer return
#' @inheritParams tidyr::pivot_longer
#'
#'
#' @seealso [tidyr::pivot_longer()]
#'
#' @export
pivot_longer <- function(data, cols, ..., cols_vary = "fastest", names_to = "name", names_prefix = NULL, names_sep = NULL, names_pattern = NULL, names_ptypes = NULL, names_transform = NULL, names_repair = "check_unique", values_to = "value", values_drop_na = FALSE, values_ptypes = NULL, values_transform = NULL) {
	.call <- match.call(definition = tidyr::pivot_longer, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::pivot_longer)
	.call$.funname <- 'pivot_longer'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::pivot_wider that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::pivot_wider()] that prints information about the operation.
#'
#' @inherit tidyr::pivot_wider return
#' @inheritParams tidyr::pivot_wider
#'
#'
#' @seealso [tidyr::pivot_wider()]
#'
#' @export
pivot_wider <- function(data, ..., id_cols = NULL, id_expand = FALSE, names_from = name, names_prefix = "", names_sep = "_", names_glue = NULL, names_sort = FALSE, names_vary = "fastest", names_expand = FALSE, names_repair = "check_unique", values_from = value, values_fill = NULL, values_fn = NULL, unused_fn = NULL) {
	.call <- match.call(definition = tidyr::pivot_wider, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::pivot_wider)
	.call$.funname <- 'pivot_wider'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::gather that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::gather()] that prints information about the operation.
#'
#' @inherit tidyr::gather return
#' @inheritParams tidyr::gather
#'
#'
#' @seealso [tidyr::gather()]
#'
#' @export
gather <- function(data, key = "key", value = "value", ..., na.rm = FALSE, convert = FALSE, factor_key = FALSE) {
	.call <- match.call(definition = tidyr::gather, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::gather)
	.call$.funname <- 'gather'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::spread that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::spread()] that prints information about the operation.
#'
#' @inherit tidyr::spread return
#' @inheritParams tidyr::spread
#'
#'
#' @seealso [tidyr::spread()]
#'
#' @export
spread <- function(data, key, value, fill = NA, convert = FALSE, drop = TRUE, sep = NULL) {
	.call <- match.call(definition = tidyr::spread, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::spread)
	.call$.funname <- 'spread'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::separate_wider_delim that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::separate_wider_delim()] that prints information about the operation.
#'
#' @inherit tidyr::separate_wider_delim return
#' @inheritParams tidyr::separate_wider_delim
#'
#'
#' @seealso [tidyr::separate_wider_delim()]
#'
#' @export
separate_wider_delim <- function(data, cols, delim, ..., names = NULL, names_sep = NULL, names_repair = "check_unique", too_few = c("error", "debug", "align_start", "align_end"), too_many = c("error", "debug", "drop", "merge"), cols_remove = TRUE) {
	.call <- match.call(definition = tidyr::separate_wider_delim, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::separate_wider_delim)
	.call$.funname <- 'separate_wider_delim'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::separate_wider_position that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::separate_wider_position()] that prints information about the operation.
#'
#' @inherit tidyr::separate_wider_position return
#' @inheritParams tidyr::separate_wider_position
#'
#'
#' @seealso [tidyr::separate_wider_position()]
#'
#' @export
separate_wider_position <- function(data, cols, widths, ..., names_sep = NULL, names_repair = "check_unique", too_few = c("error", "debug", "align_start"), too_many = c("error", "debug", "drop"), cols_remove = TRUE) {
	.call <- match.call(definition = tidyr::separate_wider_position, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::separate_wider_position)
	.call$.funname <- 'separate_wider_position'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::separate_wider_regex that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::separate_wider_regex()] that prints information about the operation.
#'
#' @inherit tidyr::separate_wider_regex return
#' @inheritParams tidyr::separate_wider_regex
#'
#'
#' @seealso [tidyr::separate_wider_regex()]
#'
#' @export
separate_wider_regex <- function(data, cols, patterns, ..., names_sep = NULL, names_repair = "check_unique", too_few = c("error", "debug", "align_start"), cols_remove = TRUE) {
	.call <- match.call(definition = tidyr::separate_wider_regex, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::separate_wider_regex)
	.call$.funname <- 'separate_wider_regex'
	eval(.call, envir = parent.frame())
}

utils::globalVariables(c('name', 'value'))
