# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_select




#' Wrapper around dplyr::select that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::select()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::select
#' @inheritDotParams dplyr::select
#'
#' @return See [dplyr::select()]
#' @seealso [dplyr::select()]
#' @export
select <- function(.data, ...) {
	result <- dplyr::select(.data, ...)
	log_select(.data, result, "select", ...)
	result
}



#' Wrapper around dplyr::select_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::select_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::select_all
#' @inheritDotParams dplyr::select_all
#'
#' @return See [dplyr::select_all()]
#' @seealso [dplyr::select_all()]
#' @export
select_all <- function(.tbl, ...) {
	result <- dplyr::select_all(.tbl, ...)
	log_select(.tbl, result, "select_all", ...)
	result
}



#' Wrapper around dplyr::select_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::select_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::select_if
#' @inheritDotParams dplyr::select_if
#'
#' @return See [dplyr::select_if()]
#' @seealso [dplyr::select_if()]
#' @export
select_if <- function(.tbl, ...) {
	result <- dplyr::select_if(.tbl, ...)
	log_select(.tbl, result, "select_if", ...)
	result
}



#' Wrapper around dplyr::select_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::select_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::select_at
#' @inheritDotParams dplyr::select_at
#'
#' @return See [dplyr::select_at()]
#' @seealso [dplyr::select_at()]
#' @export
select_at <- function(.tbl, ...) {
	result <- dplyr::select_at(.tbl, ...)
	log_select(.tbl, result, "select_at", ...)
	result
}



#' Wrapper around dplyr::relocate that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::relocate()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::relocate
#' @inheritDotParams dplyr::relocate
#'
#' @return See [dplyr::relocate()]
#' @seealso [dplyr::relocate()]
#' @export
relocate <- function(.data, ...) {
	result <- dplyr::relocate(.data, ...)
	log_select(.data, result, "relocate", ...)
	result
}


