# Generated by tools/generate_wrappers.R: do not edit by hand

# Logger category: log_arrange


#' Wrapper around dplyr::arrange that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::arrange()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.1.
#'
#' @inheritParams dplyr::arrange
#' @inheritDotParams dplyr::arrange
#'
#' @return See [dplyr::arrange()]
#' @seealso [dplyr::arrange()]
#' @export
arrange <- function(.data, ...) {
	result <- dplyr::arrange(.data, ...)
	log_arrange(.data, result, "arrange", ...)
	result
}


