# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_longer_wider




#' Wrapper around tidyr::pivot_longer that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::pivot_longer()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::pivot_longer
#' @inheritDotParams tidyr::pivot_longer
#'
#' @return See [tidyr::pivot_longer()]
#' @seealso [tidyr::pivot_longer()]
#' @export
pivot_longer <- function(data, ...) {
	result <- tidyr::pivot_longer(data, ...)
	log_longer_wider(data, result, "pivot_longer")
	result
}



#' Wrapper around tidyr::pivot_wider that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::pivot_wider()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::pivot_wider
#' @inheritDotParams tidyr::pivot_wider
#'
#' @return See [tidyr::pivot_wider()]
#' @seealso [tidyr::pivot_wider()]
#' @export
pivot_wider <- function(data, ...) {
	result <- tidyr::pivot_wider(data, ...)
	log_longer_wider(data, result, "pivot_wider")
	result
}



#' Wrapper around tidyr::gather that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::gather()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::gather
#' @inheritDotParams tidyr::gather
#'
#' @return See [tidyr::gather()]
#' @seealso [tidyr::gather()]
#' @export
gather <- function(data, ...) {
	result <- tidyr::gather(data, ...)
	log_longer_wider(data, result, "gather")
	result
}



#' Wrapper around tidyr::spread that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::spread()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::spread
#' @inheritDotParams tidyr::spread
#'
#' @return See [tidyr::spread()]
#' @seealso [tidyr::spread()]
#' @export
spread <- function(data, ...) {
	result <- tidyr::spread(data, ...)
	log_longer_wider(data, result, "spread")
	result
}



#' Wrapper around tidyr::separate_wider_delim that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::separate_wider_delim()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::separate_wider_delim
#' @inheritDotParams tidyr::separate_wider_delim
#'
#' @return See [tidyr::separate_wider_delim()]
#' @seealso [tidyr::separate_wider_delim()]
#' @export
separate_wider_delim <- function(data, ...) {
	result <- tidyr::separate_wider_delim(data, ...)
	log_longer_wider(data, result, "separate_wider_delim")
	result
}



#' Wrapper around tidyr::separate_wider_position that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::separate_wider_position()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::separate_wider_position
#' @inheritDotParams tidyr::separate_wider_position
#'
#' @return See [tidyr::separate_wider_position()]
#' @seealso [tidyr::separate_wider_position()]
#' @export
separate_wider_position <- function(data, ...) {
	result <- tidyr::separate_wider_position(data, ...)
	log_longer_wider(data, result, "separate_wider_position")
	result
}



#' Wrapper around tidyr::separate_wider_regex that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::separate_wider_regex()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::separate_wider_regex
#' @inheritDotParams tidyr::separate_wider_regex
#'
#' @return See [tidyr::separate_wider_regex()]
#' @seealso [tidyr::separate_wider_regex()]
#' @export
separate_wider_regex <- function(data, ...) {
	result <- tidyr::separate_wider_regex(data, ...)
	log_longer_wider(data, result, "separate_wider_regex")
	result
}


utils::globalVariables(c('name', 'value'))

