# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_summarize



#' Wrapper around dplyr::summarize that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize()] that prints information about the operation.
#'
#' @inherit dplyr::summarize return
#' @inheritParams dplyr::summarize
#'
#'
#' @seealso [dplyr::summarize()]
#'
#' @export
summarize <- function(.data, ..., .by = NULL, .groups = NULL) {
	.call <- match.call(definition = dplyr::summarize, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize)
	.call$.funname <- 'summarize'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize_all()] that prints information about the operation.
#'
#' @inherit dplyr::summarize_all return
#' @inheritParams dplyr::summarize_all
#'
#'
#' @seealso [dplyr::summarize_all()]
#'
#' @export
summarize_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::summarize_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize_all)
	.call$.funname <- 'summarize_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize_at()] that prints information about the operation.
#'
#' @inherit dplyr::summarize_at return
#' @inheritParams dplyr::summarize_at
#'
#'
#' @seealso [dplyr::summarize_at()]
#'
#' @export
summarize_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::summarize_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize_at)
	.call$.funname <- 'summarize_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarize_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarize_if()] that prints information about the operation.
#'
#' @inherit dplyr::summarize_if return
#' @inheritParams dplyr::summarize_if
#'
#'
#' @seealso [dplyr::summarize_if()]
#'
#' @export
summarize_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::summarize_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarize_if)
	.call$.funname <- 'summarize_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise()] that prints information about the operation.
#'
#' @inherit dplyr::summarise return
#' @inheritParams dplyr::summarise
#'
#'
#' @seealso [dplyr::summarise()]
#'
#' @export
summarise <- function(.data, ..., .by = NULL, .groups = NULL) {
	.call <- match.call(definition = dplyr::summarise, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise)
	.call$.funname <- 'summarise'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise_all()] that prints information about the operation.
#'
#' @inherit dplyr::summarise_all return
#' @inheritParams dplyr::summarise_all
#'
#'
#' @seealso [dplyr::summarise_all()]
#'
#' @export
summarise_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::summarise_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise_all)
	.call$.funname <- 'summarise_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise_at()] that prints information about the operation.
#'
#' @inherit dplyr::summarise_at return
#' @inheritParams dplyr::summarise_at
#'
#'
#' @seealso [dplyr::summarise_at()]
#'
#' @export
summarise_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::summarise_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise_at)
	.call$.funname <- 'summarise_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::summarise_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::summarise_if()] that prints information about the operation.
#'
#' @inherit dplyr::summarise_if return
#' @inheritParams dplyr::summarise_if
#'
#'
#' @seealso [dplyr::summarise_if()]
#'
#' @export
summarise_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::summarise_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::summarise_if)
	.call$.funname <- 'summarise_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::tally that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::tally()] that prints information about the operation.
#'
#' @inherit dplyr::tally return
#' @inheritParams dplyr::tally
#'
#'
#' @seealso [dplyr::tally()]
#'
#' @export
tally <- function(x, wt = NULL, sort = FALSE, name = NULL) {
	.call <- match.call(definition = dplyr::tally, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::tally)
	.call$.funname <- 'tally'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::count that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::count()] that prints information about the operation.
#'
#' @inherit dplyr::count return
#' @inheritParams dplyr::count
#'
#'
#' @seealso [dplyr::count()]
#'
#' @export
count <- function(x, ..., wt = NULL, sort = FALSE, name = NULL) {
	.call <- match.call(definition = dplyr::count, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(dplyr::count)
	.call$.funname <- 'count'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::uncount that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::uncount()] that prints information about the operation.
#'
#' @inherit tidyr::uncount return
#' @inheritParams tidyr::uncount
#'
#'
#' @seealso [tidyr::uncount()]
#'
#' @export
uncount <- function(data, weights, ..., .remove = TRUE, .id = NULL) {
	.call <- match.call(definition = tidyr::uncount, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_summarize
	.call$.fun <- quote(tidyr::uncount)
	.call$.funname <- 'uncount'
	eval(.call, envir = parent.frame())
}


