# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_filter




#' Wrapper around dplyr::filter that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::filter()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::filter
#' @inheritDotParams dplyr::filter
#'
#' @return See [dplyr::filter()]
#' @seealso [dplyr::filter()]
#' @export
filter <- function(.data, ...) {
	result <- dplyr::filter(.data, ...)
	log_filter(.data, result, "filter")
	result
}



#' Wrapper around dplyr::filter_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::filter_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::filter_all
#' @inheritDotParams dplyr::filter_all
#'
#' @return See [dplyr::filter_all()]
#' @seealso [dplyr::filter_all()]
#' @export
filter_all <- function(.tbl, ...) {
	result <- dplyr::filter_all(.tbl, ...)
	log_filter(.tbl, result, "filter_all")
	result
}



#' Wrapper around dplyr::filter_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::filter_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::filter_if
#' @inheritDotParams dplyr::filter_if
#'
#' @return See [dplyr::filter_if()]
#' @seealso [dplyr::filter_if()]
#' @export
filter_if <- function(.tbl, ...) {
	result <- dplyr::filter_if(.tbl, ...)
	log_filter(.tbl, result, "filter_if")
	result
}



#' Wrapper around dplyr::filter_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::filter_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::filter_at
#' @inheritDotParams dplyr::filter_at
#'
#' @return See [dplyr::filter_at()]
#' @seealso [dplyr::filter_at()]
#' @export
filter_at <- function(.tbl, ...) {
	result <- dplyr::filter_at(.tbl, ...)
	log_filter(.tbl, result, "filter_at")
	result
}



#' Wrapper around dplyr::distinct that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::distinct()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::distinct
#' @inheritDotParams dplyr::distinct
#'
#' @return See [dplyr::distinct()]
#' @seealso [dplyr::distinct()]
#' @export
distinct <- function(.data, ...) {
	result <- dplyr::distinct(.data, ...)
	log_filter(.data, result, "distinct")
	result
}



#' Wrapper around dplyr::distinct_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::distinct_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::distinct_all
#' @inheritDotParams dplyr::distinct_all
#'
#' @return See [dplyr::distinct_all()]
#' @seealso [dplyr::distinct_all()]
#' @export
distinct_all <- function(.tbl, ...) {
	result <- dplyr::distinct_all(.tbl, ...)
	log_filter(.tbl, result, "distinct_all")
	result
}



#' Wrapper around dplyr::distinct_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::distinct_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::distinct_if
#' @inheritDotParams dplyr::distinct_if
#'
#' @return See [dplyr::distinct_if()]
#' @seealso [dplyr::distinct_if()]
#' @export
distinct_if <- function(.tbl, ...) {
	result <- dplyr::distinct_if(.tbl, ...)
	log_filter(.tbl, result, "distinct_if")
	result
}



#' Wrapper around dplyr::distinct_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::distinct_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::distinct_at
#' @inheritDotParams dplyr::distinct_at
#'
#' @return See [dplyr::distinct_at()]
#' @seealso [dplyr::distinct_at()]
#' @export
distinct_at <- function(.tbl, ...) {
	result <- dplyr::distinct_at(.tbl, ...)
	log_filter(.tbl, result, "distinct_at")
	result
}



#' Wrapper around dplyr::top_n that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::top_n()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::top_n
#' @inheritDotParams dplyr::top_n
#'
#' @return See [dplyr::top_n()]
#' @seealso [dplyr::top_n()]
#' @export
top_n <- function(x, ...) {
	result <- dplyr::top_n(x, ...)
	log_filter(x, result, "top_n")
	result
}



#' Wrapper around dplyr::top_frac that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::top_frac()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::top_frac
#' @inheritDotParams dplyr::top_frac
#'
#' @return See [dplyr::top_frac()]
#' @seealso [dplyr::top_frac()]
#' @export
top_frac <- function(x, ...) {
	result <- dplyr::top_frac(x, ...)
	log_filter(x, result, "top_frac")
	result
}



#' Wrapper around dplyr::sample_n that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::sample_n()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::sample_n
#' @inheritDotParams dplyr::sample_n
#'
#' @return See [dplyr::sample_n()]
#' @seealso [dplyr::sample_n()]
#' @export
sample_n <- function(tbl, ...) {
	result <- dplyr::sample_n(tbl, ...)
	log_filter(tbl, result, "sample_n")
	result
}



#' Wrapper around dplyr::sample_frac that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::sample_frac()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::sample_frac
#' @inheritDotParams dplyr::sample_frac
#'
#' @return See [dplyr::sample_frac()]
#' @seealso [dplyr::sample_frac()]
#' @export
sample_frac <- function(tbl, ...) {
	result <- dplyr::sample_frac(tbl, ...)
	log_filter(tbl, result, "sample_frac")
	result
}



#' Wrapper around dplyr::slice that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::slice()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::slice
#' @inheritDotParams dplyr::slice
#'
#' @return See [dplyr::slice()]
#' @seealso [dplyr::slice()]
#' @export
slice <- function(.data, ...) {
	result <- dplyr::slice(.data, ...)
	log_filter(.data, result, "slice")
	result
}



#' Wrapper around dplyr::slice_head that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::slice_head()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::slice_head
#' @inheritDotParams dplyr::slice_head
#'
#' @return See [dplyr::slice_head()]
#' @seealso [dplyr::slice_head()]
#' @export
slice_head <- function(.data, ...) {
	result <- dplyr::slice_head(.data, ...)
	log_filter(.data, result, "slice_head")
	result
}



#' Wrapper around dplyr::slice_tail that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::slice_tail()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::slice_tail
#' @inheritDotParams dplyr::slice_tail
#'
#' @return See [dplyr::slice_tail()]
#' @seealso [dplyr::slice_tail()]
#' @export
slice_tail <- function(.data, ...) {
	result <- dplyr::slice_tail(.data, ...)
	log_filter(.data, result, "slice_tail")
	result
}



#' Wrapper around dplyr::slice_min that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::slice_min()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::slice_min
#' @inheritDotParams dplyr::slice_min
#'
#' @return See [dplyr::slice_min()]
#' @seealso [dplyr::slice_min()]
#' @export
slice_min <- function(.data, ...) {
	result <- dplyr::slice_min(.data, ...)
	log_filter(.data, result, "slice_min")
	result
}



#' Wrapper around dplyr::slice_max that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::slice_max()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::slice_max
#' @inheritDotParams dplyr::slice_max
#'
#' @return See [dplyr::slice_max()]
#' @seealso [dplyr::slice_max()]
#' @export
slice_max <- function(.data, ...) {
	result <- dplyr::slice_max(.data, ...)
	log_filter(.data, result, "slice_max")
	result
}



#' Wrapper around dplyr::slice_sample that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::slice_sample()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::slice_sample
#' @inheritDotParams dplyr::slice_sample
#'
#' @return See [dplyr::slice_sample()]
#' @seealso [dplyr::slice_sample()]
#' @export
slice_sample <- function(.data, ...) {
	result <- dplyr::slice_sample(.data, ...)
	log_filter(.data, result, "slice_sample")
	result
}



#' Wrapper around tidyr::drop_na that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::drop_na()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::drop_na
#' @inheritDotParams tidyr::drop_na
#'
#' @return See [tidyr::drop_na()]
#' @seealso [tidyr::drop_na()]
#' @export
drop_na <- function(data, ...) {
	result <- tidyr::drop_na(data, ...)
	log_filter(data, result, "drop_na")
	result
}


