# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_longer_wider



#' Wrapper around tidyr::pivot_longer that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::pivot_longer()] that prints information about the operation.
#'
#' @inherit tidyr::pivot_longer return
#' @inheritParams tidyr::pivot_longer
#'
#'
#' @seealso [tidyr::pivot_longer()]
#'
#' @export
pivot_longer <- function(data, cols, ..., cols_vary = "fastest", names_to = "name", names_prefix = NULL, names_sep = NULL, names_pattern = NULL, names_ptypes = NULL, names_transform = NULL, names_repair = "check_unique", values_to = "value", values_drop_na = FALSE, values_ptypes = NULL, values_transform = NULL) {
	.call <- match.call(definition = tidyr::pivot_longer, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::pivot_longer)
	.call$.funname <- 'pivot_longer'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::pivot_wider that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::pivot_wider()] that prints information about the operation.
#'
#' @inherit tidyr::pivot_wider return
#' @inheritParams tidyr::pivot_wider
#'
#'
#' @seealso [tidyr::pivot_wider()]
#'
#' @export
pivot_wider <- function(data, ..., id_cols = NULL, id_expand = FALSE, names_from = name, names_prefix = "", names_sep = "_", names_glue = NULL, names_sort = FALSE, names_vary = "fastest", names_expand = FALSE, names_repair = "check_unique", values_from = value, values_fill = NULL, values_fn = NULL, unused_fn = NULL) {
	.call <- match.call(definition = tidyr::pivot_wider, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::pivot_wider)
	.call$.funname <- 'pivot_wider'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::gather that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::gather()] that prints information about the operation.
#'
#' @inherit tidyr::gather return
#' @inheritParams tidyr::gather
#'
#'
#' @seealso [tidyr::gather()]
#'
#' @export
gather <- function(data, key = "key", value = "value", ..., na.rm = FALSE, convert = FALSE, factor_key = FALSE) {
	.call <- match.call(definition = tidyr::gather, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::gather)
	.call$.funname <- 'gather'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::spread that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::spread()] that prints information about the operation.
#'
#' @inherit tidyr::spread return
#' @inheritParams tidyr::spread
#'
#'
#' @seealso [tidyr::spread()]
#'
#' @export
spread <- function(data, key, value, fill = NA, convert = FALSE, drop = TRUE, sep = NULL) {
	.call <- match.call(definition = tidyr::spread, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::spread)
	.call$.funname <- 'spread'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::separate_wider_delim that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::separate_wider_delim()] that prints information about the operation.
#'
#' @inherit tidyr::separate_wider_delim return
#' @inheritParams tidyr::separate_wider_delim
#'
#'
#' @seealso [tidyr::separate_wider_delim()]
#'
#' @export
separate_wider_delim <- function(data, cols, delim, ..., names = NULL, names_sep = NULL, names_repair = "check_unique", too_few = c("error", "debug", "align_start", "align_end"), too_many = c("error", "debug", "drop", "merge"), cols_remove = TRUE) {
	.call <- match.call(definition = tidyr::separate_wider_delim, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::separate_wider_delim)
	.call$.funname <- 'separate_wider_delim'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::separate_wider_position that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::separate_wider_position()] that prints information about the operation.
#'
#' @inherit tidyr::separate_wider_position return
#' @inheritParams tidyr::separate_wider_position
#'
#'
#' @seealso [tidyr::separate_wider_position()]
#'
#' @export
separate_wider_position <- function(data, cols, widths, ..., names_sep = NULL, names_repair = "check_unique", too_few = c("error", "debug", "align_start"), too_many = c("error", "debug", "drop"), cols_remove = TRUE) {
	.call <- match.call(definition = tidyr::separate_wider_position, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::separate_wider_position)
	.call$.funname <- 'separate_wider_position'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::separate_wider_regex that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::separate_wider_regex()] that prints information about the operation.
#'
#' @inherit tidyr::separate_wider_regex return
#' @inheritParams tidyr::separate_wider_regex
#'
#'
#' @seealso [tidyr::separate_wider_regex()]
#'
#' @export
separate_wider_regex <- function(data, cols, patterns, ..., names_sep = NULL, names_repair = "check_unique", too_few = c("error", "debug", "align_start"), cols_remove = TRUE) {
	.call <- match.call(definition = tidyr::separate_wider_regex, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_longer_wider
	.call$.fun <- quote(tidyr::separate_wider_regex)
	.call$.funname <- 'separate_wider_regex'
	eval(.call, envir = parent.frame())
}


utils::globalVariables(c('name', 'value'))

