# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_join



#' Wrapper around dplyr::inner_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::inner_join()] that prints information about the operation.
#'
#' @inherit dplyr::inner_join return
#' @inheritParams dplyr::inner_join
#'
#'
#' @seealso [dplyr::inner_join()]
#'
#' @export
inner_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::inner_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::inner_join)
	.call$.funname <- 'inner_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::full_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::full_join()] that prints information about the operation.
#'
#' @inherit dplyr::full_join return
#' @inheritParams dplyr::full_join
#'
#'
#' @seealso [dplyr::full_join()]
#'
#' @export
full_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::full_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::full_join)
	.call$.funname <- 'full_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::left_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::left_join()] that prints information about the operation.
#'
#' @inherit dplyr::left_join return
#' @inheritParams dplyr::left_join
#'
#'
#' @seealso [dplyr::left_join()]
#'
#' @export
left_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::left_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::left_join)
	.call$.funname <- 'left_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::right_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::right_join()] that prints information about the operation.
#'
#' @inherit dplyr::right_join return
#' @inheritParams dplyr::right_join
#'
#'
#' @seealso [dplyr::right_join()]
#'
#' @export
right_join <- function(x, y, by = NULL, copy = FALSE, suffix = c(".x", ".y"), ..., keep = NULL) {
	.call <- match.call(definition = dplyr::right_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::right_join)
	.call$.funname <- 'right_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::anti_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::anti_join()] that prints information about the operation.
#'
#' @inherit dplyr::anti_join return
#' @inheritParams dplyr::anti_join
#'
#'
#' @seealso [dplyr::anti_join()]
#'
#' @export
anti_join <- function(x, y, by = NULL, copy = FALSE, ...) {
	.call <- match.call(definition = dplyr::anti_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::anti_join)
	.call$.funname <- 'anti_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::semi_join that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::semi_join()] that prints information about the operation.
#'
#' @inherit dplyr::semi_join return
#' @inheritParams dplyr::semi_join
#'
#'
#' @seealso [dplyr::semi_join()]
#'
#' @export
semi_join <- function(x, y, by = NULL, copy = FALSE, ...) {
	.call <- match.call(definition = dplyr::semi_join, expand.dots = TRUE)
	.call[[1]] <- log_join
	.call$.fun <- quote(dplyr::semi_join)
	.call$.funname <- 'semi_join'
	.call$.name_x <- deparse1(substitute(x))
	.call$.name_y <- deparse1(substitute(y))
	eval(.call, envir = parent.frame())
}


