# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_rename



#' Wrapper around dplyr::rename that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename()] that prints information about the operation.
#'
#' @inherit dplyr::rename return
#' @inheritParams dplyr::rename
#'
#'
#' @seealso [dplyr::rename()]
#'
#' @export
rename <- function(.data, ...) {
	.call <- match.call(definition = dplyr::rename, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename)
	.call$.funname <- 'rename'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_all()] that prints information about the operation.
#'
#' @inherit dplyr::rename_all return
#' @inheritParams dplyr::rename_all
#'
#'
#' @seealso [dplyr::rename_all()]
#'
#' @export
rename_all <- function(.tbl, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::rename_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_all)
	.call$.funname <- 'rename_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_if()] that prints information about the operation.
#'
#' @inherit dplyr::rename_if return
#' @inheritParams dplyr::rename_if
#'
#'
#' @seealso [dplyr::rename_if()]
#'
#' @export
rename_if <- function(.tbl, .predicate, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::rename_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_if)
	.call$.funname <- 'rename_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_at()] that prints information about the operation.
#'
#' @inherit dplyr::rename_at return
#' @inheritParams dplyr::rename_at
#'
#'
#' @seealso [dplyr::rename_at()]
#'
#' @export
rename_at <- function(.tbl, .vars, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::rename_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_at)
	.call$.funname <- 'rename_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::rename_with that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::rename_with()] that prints information about the operation.
#'
#' @inherit dplyr::rename_with return
#' @inheritParams dplyr::rename_with
#' @importFrom tidyselect everything
#'
#' @seealso [dplyr::rename_with()]
#'
#' @export
rename_with <- function(.data, .fn, .cols = everything(), ...) {
	.call <- match.call(definition = dplyr::rename_with, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_rename
	.call$.fun <- quote(dplyr::rename_with)
	.call$.funname <- 'rename_with'
	eval(.call, envir = parent.frame())
}


