# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: log_group_by


#' Wrapper around dplyr::group_by that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::group_by()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::group_by
#' @inheritDotParams dplyr::group_by
#'
#' @return See [dplyr::group_by()]
#' @seealso [dplyr::group_by()]
#' @export
group_by <- function(.data, ...) {
	result <- dplyr::group_by(.data, ...)
	log_group_by(.data, result, "group_by", ...)
	result
}



#' Wrapper around dplyr::group_by_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::group_by_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::group_by_all
#' @inheritDotParams dplyr::group_by_all
#'
#' @return See [dplyr::group_by_all()]
#' @seealso [dplyr::group_by_all()]
#' @export
group_by_all <- function(.tbl, ...) {
	result <- dplyr::group_by_all(.tbl, ...)
	log_group_by(.tbl, result, "group_by_all", ...)
	result
}



#' Wrapper around dplyr::group_by_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::group_by_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::group_by_at
#' @inheritDotParams dplyr::group_by_at
#'
#' @return See [dplyr::group_by_at()]
#' @seealso [dplyr::group_by_at()]
#' @export
group_by_at <- function(.tbl, ...) {
	result <- dplyr::group_by_at(.tbl, ...)
	log_group_by(.tbl, result, "group_by_at", ...)
	result
}



#' Wrapper around dplyr::group_by_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::group_by_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::group_by_if
#' @inheritDotParams dplyr::group_by_if
#'
#' @return See [dplyr::group_by_if()]
#' @seealso [dplyr::group_by_if()]
#' @export
group_by_if <- function(.tbl, ...) {
	result <- dplyr::group_by_if(.tbl, ...)
	log_group_by(.tbl, result, "group_by_if", ...)
	result
}



#' Wrapper around dplyr::ungroup that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::ungroup()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::ungroup
#' 
#'
#' @return See [dplyr::ungroup()]
#' @seealso [dplyr::ungroup()]
#' @export
ungroup <- function(x, ...) {
	result <- dplyr::ungroup(x, ...)
	log_group_by(x, result, "ungroup", ...)
	result
}


