# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: log_rename


#' Wrapper around dplyr::rename that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::rename()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::rename
#' 
#'
#' @return See [dplyr::rename()]
#' @seealso [dplyr::rename()]
#' @export
rename <- function(.data, ...) {
	result <- dplyr::rename(.data, ...)
	log_rename(.data, result, "rename", ...)
	result
}



#' Wrapper around dplyr::rename_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::rename_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::rename_all
#' @inheritDotParams dplyr::rename_all
#'
#' @return See [dplyr::rename_all()]
#' @seealso [dplyr::rename_all()]
#' @export
rename_all <- function(.tbl, ...) {
	result <- dplyr::rename_all(.tbl, ...)
	log_rename(.tbl, result, "rename_all", ...)
	result
}



#' Wrapper around dplyr::rename_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::rename_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::rename_if
#' @inheritDotParams dplyr::rename_if
#'
#' @return See [dplyr::rename_if()]
#' @seealso [dplyr::rename_if()]
#' @export
rename_if <- function(.tbl, ...) {
	result <- dplyr::rename_if(.tbl, ...)
	log_rename(.tbl, result, "rename_if", ...)
	result
}



#' Wrapper around dplyr::rename_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::rename_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::rename_at
#' @inheritDotParams dplyr::rename_at
#'
#' @return See [dplyr::rename_at()]
#' @seealso [dplyr::rename_at()]
#' @export
rename_at <- function(.tbl, ...) {
	result <- dplyr::rename_at(.tbl, ...)
	log_rename(.tbl, result, "rename_at", ...)
	result
}



#' Wrapper around dplyr::rename_with that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::rename_with()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::rename_with
#' @inheritDotParams dplyr::rename_with
#'
#' @return See [dplyr::rename_with()]
#' @seealso [dplyr::rename_with()]
#' @export
rename_with <- function(.data, ...) {
	result <- dplyr::rename_with(.data, ...)
	log_rename(.data, result, "rename_with", ...)
	result
}


