# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_select



#' Wrapper around dplyr::select that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select()] that prints information about the operation.
#'
#' @inherit dplyr::select return
#' @inheritParams dplyr::select
#'
#'
#' @seealso [dplyr::select()]
#'
#' @export
select <- function(.data, ...) {
	.call <- match.call(definition = dplyr::select, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select)
	.call$.funname <- 'select'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select_all()] that prints information about the operation.
#'
#' @inherit dplyr::select_all return
#' @inheritParams dplyr::select_all
#'
#'
#' @seealso [dplyr::select_all()]
#'
#' @export
select_all <- function(.tbl, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::select_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select_all)
	.call$.funname <- 'select_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select_if()] that prints information about the operation.
#'
#' @inherit dplyr::select_if return
#' @inheritParams dplyr::select_if
#'
#'
#' @seealso [dplyr::select_if()]
#'
#' @export
select_if <- function(.tbl, .predicate, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::select_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select_if)
	.call$.funname <- 'select_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::select_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::select_at()] that prints information about the operation.
#'
#' @inherit dplyr::select_at return
#' @inheritParams dplyr::select_at
#'
#'
#' @seealso [dplyr::select_at()]
#'
#' @export
select_at <- function(.tbl, .vars, .funs = list(), ...) {
	.call <- match.call(definition = dplyr::select_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::select_at)
	.call$.funname <- 'select_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::relocate that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::relocate()] that prints information about the operation.
#'
#' @inherit dplyr::relocate return
#' @inheritParams dplyr::relocate
#'
#'
#' @seealso [dplyr::relocate()]
#'
#' @export
relocate <- function(.data, ..., .before = NULL, .after = NULL) {
	.call <- match.call(definition = dplyr::relocate, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_select
	.call$.fun <- quote(dplyr::relocate)
	.call$.funname <- 'relocate'
	eval(.call, envir = parent.frame())
}


