# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: log_join


#' Wrapper around dplyr::inner_join that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::inner_join()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::inner_join
#' @inheritDotParams dplyr::inner_join
#'
#' @return See [dplyr::inner_join()]
#' @seealso [dplyr::inner_join()]
#' @export
inner_join <- function(x, y, by = NULL, ...) {
	result <- dplyr::inner_join(x, y, by = by, ...)
	log_join(x, y, by, result, "inner_join",
	              .name_x = deparse1(substitute(x)),
	              .name_y = deparse1(substitute(y)), ...)
	result
}



#' Wrapper around dplyr::full_join that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::full_join()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::full_join
#' @inheritDotParams dplyr::full_join
#'
#' @return See [dplyr::full_join()]
#' @seealso [dplyr::full_join()]
#' @export
full_join <- function(x, y, by = NULL, ...) {
	result <- dplyr::full_join(x, y, by = by, ...)
	log_join(x, y, by, result, "full_join",
	              .name_x = deparse1(substitute(x)),
	              .name_y = deparse1(substitute(y)), ...)
	result
}



#' Wrapper around dplyr::left_join that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::left_join()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::left_join
#' @inheritDotParams dplyr::left_join
#'
#' @return See [dplyr::left_join()]
#' @seealso [dplyr::left_join()]
#' @export
left_join <- function(x, y, by = NULL, ...) {
	result <- dplyr::left_join(x, y, by = by, ...)
	log_join(x, y, by, result, "left_join",
	              .name_x = deparse1(substitute(x)),
	              .name_y = deparse1(substitute(y)), ...)
	result
}



#' Wrapper around dplyr::right_join that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::right_join()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::right_join
#' @inheritDotParams dplyr::right_join
#'
#' @return See [dplyr::right_join()]
#' @seealso [dplyr::right_join()]
#' @export
right_join <- function(x, y, by = NULL, ...) {
	result <- dplyr::right_join(x, y, by = by, ...)
	log_join(x, y, by, result, "right_join",
	              .name_x = deparse1(substitute(x)),
	              .name_y = deparse1(substitute(y)), ...)
	result
}



#' Wrapper around dplyr::anti_join that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::anti_join()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::anti_join
#' @inheritDotParams dplyr::anti_join
#'
#' @return See [dplyr::anti_join()]
#' @seealso [dplyr::anti_join()]
#' @export
anti_join <- function(x, y, by = NULL, ...) {
	result <- dplyr::anti_join(x, y, by = by, ...)
	log_join(x, y, by, result, "anti_join",
	              .name_x = deparse1(substitute(x)),
	              .name_y = deparse1(substitute(y)), ...)
	result
}



#' Wrapper around dplyr::semi_join that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::semi_join()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::semi_join
#' @inheritDotParams dplyr::semi_join
#'
#' @return See [dplyr::semi_join()]
#' @seealso [dplyr::semi_join()]
#' @export
semi_join <- function(x, y, by = NULL, ...) {
	result <- dplyr::semi_join(x, y, by = by, ...)
	log_join(x, y, by, result, "semi_join",
	              .name_x = deparse1(substitute(x)),
	              .name_y = deparse1(substitute(y)), ...)
	result
}


