# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_group_by



#' Wrapper around dplyr::group_by that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by()] that prints information about the operation.
#'
#' @inherit dplyr::group_by return
#' @inheritParams dplyr::group_by
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by()]
#'
#' @export
group_by <- function(.data, ..., .add = FALSE, .drop = group_by_drop_default(.data)) {
	.call <- match.call(definition = dplyr::group_by, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by)
	.call$.funname <- 'group_by'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by_all()] that prints information about the operation.
#'
#' @inherit dplyr::group_by_all return
#' @inheritParams dplyr::group_by_all
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by_all()]
#'
#' @export
group_by_all <- function(.tbl, .funs = list(), ..., .add = FALSE, .drop = group_by_drop_default(.tbl)) {
	.call <- match.call(definition = dplyr::group_by_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by_all)
	.call$.funname <- 'group_by_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by_at()] that prints information about the operation.
#'
#' @inherit dplyr::group_by_at return
#' @inheritParams dplyr::group_by_at
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by_at()]
#'
#' @export
group_by_at <- function(.tbl, .vars, .funs = list(), ..., .add = FALSE, .drop = group_by_drop_default(.tbl)) {
	.call <- match.call(definition = dplyr::group_by_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by_at)
	.call$.funname <- 'group_by_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::group_by_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::group_by_if()] that prints information about the operation.
#'
#' @inherit dplyr::group_by_if return
#' @inheritParams dplyr::group_by_if
#' @importFrom dplyr group_by_drop_default
#'
#' @seealso [dplyr::group_by_if()]
#'
#' @export
group_by_if <- function(.tbl, .predicate, .funs = list(), ..., .add = FALSE, .drop = group_by_drop_default(.tbl)) {
	.call <- match.call(definition = dplyr::group_by_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::group_by_if)
	.call$.funname <- 'group_by_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::ungroup that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::ungroup()] that prints information about the operation.
#'
#' @inherit dplyr::ungroup return
#' @inheritParams dplyr::ungroup
#'
#'
#' @seealso [dplyr::ungroup()]
#'
#' @export
ungroup <- function(x, ...) {
	.call <- match.call(definition = dplyr::ungroup, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_group_by
	.call$.fun <- quote(dplyr::ungroup)
	.call$.funname <- 'ungroup'
	eval(.call, envir = parent.frame())
}


