# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_summarize




#' Wrapper around dplyr::summarize that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarize()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarize
#' @inheritDotParams dplyr::summarize
#'
#' @return See [dplyr::summarize()]
#' @seealso [dplyr::summarize()]
#' @export
summarize <- function(.data, ...) {
	result <- dplyr::summarize(.data, ...)
	log_summarize(.data, result, "summarize", ...)
	result
}



#' Wrapper around dplyr::summarize_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarize_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarize_all
#' @inheritDotParams dplyr::summarize_all
#'
#' @return See [dplyr::summarize_all()]
#' @seealso [dplyr::summarize_all()]
#' @export
summarize_all <- function(.tbl, ...) {
	result <- dplyr::summarize_all(.tbl, ...)
	log_summarize(.tbl, result, "summarize_all", ...)
	result
}



#' Wrapper around dplyr::summarize_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarize_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarize_at
#' @inheritDotParams dplyr::summarize_at
#'
#' @return See [dplyr::summarize_at()]
#' @seealso [dplyr::summarize_at()]
#' @export
summarize_at <- function(.tbl, ...) {
	result <- dplyr::summarize_at(.tbl, ...)
	log_summarize(.tbl, result, "summarize_at", ...)
	result
}



#' Wrapper around dplyr::summarize_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarize_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarize_if
#' @inheritDotParams dplyr::summarize_if
#'
#' @return See [dplyr::summarize_if()]
#' @seealso [dplyr::summarize_if()]
#' @export
summarize_if <- function(.tbl, ...) {
	result <- dplyr::summarize_if(.tbl, ...)
	log_summarize(.tbl, result, "summarize_if", ...)
	result
}



#' Wrapper around dplyr::summarise that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarise()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarise
#' @inheritDotParams dplyr::summarise
#'
#' @return See [dplyr::summarise()]
#' @seealso [dplyr::summarise()]
#' @export
summarise <- function(.data, ...) {
	result <- dplyr::summarise(.data, ...)
	log_summarize(.data, result, "summarise", ...)
	result
}



#' Wrapper around dplyr::summarise_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarise_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarise_all
#' @inheritDotParams dplyr::summarise_all
#'
#' @return See [dplyr::summarise_all()]
#' @seealso [dplyr::summarise_all()]
#' @export
summarise_all <- function(.tbl, ...) {
	result <- dplyr::summarise_all(.tbl, ...)
	log_summarize(.tbl, result, "summarise_all", ...)
	result
}



#' Wrapper around dplyr::summarise_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarise_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarise_at
#' @inheritDotParams dplyr::summarise_at
#'
#' @return See [dplyr::summarise_at()]
#' @seealso [dplyr::summarise_at()]
#' @export
summarise_at <- function(.tbl, ...) {
	result <- dplyr::summarise_at(.tbl, ...)
	log_summarize(.tbl, result, "summarise_at", ...)
	result
}



#' Wrapper around dplyr::summarise_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::summarise_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::summarise_if
#' @inheritDotParams dplyr::summarise_if
#'
#' @return See [dplyr::summarise_if()]
#' @seealso [dplyr::summarise_if()]
#' @export
summarise_if <- function(.tbl, ...) {
	result <- dplyr::summarise_if(.tbl, ...)
	log_summarize(.tbl, result, "summarise_if", ...)
	result
}



#' Wrapper around dplyr::tally that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::tally()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::tally
#' @inheritDotParams dplyr::tally
#'
#' @return See [dplyr::tally()]
#' @seealso [dplyr::tally()]
#' @export
tally <- function(x, ...) {
	result <- dplyr::tally(x, ...)
	log_summarize(x, result, "tally", ...)
	result
}



#' Wrapper around dplyr::count that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::count()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::count
#' @inheritDotParams dplyr::count
#'
#' @return See [dplyr::count()]
#' @seealso [dplyr::count()]
#' @export
count <- function(x, ...) {
	result <- dplyr::count(x, ...)
	log_summarize(x, result, "count", ...)
	result
}



#' Wrapper around tidyr::uncount that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::uncount()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::uncount
#' @inheritDotParams tidyr::uncount
#'
#' @return See [tidyr::uncount()]
#' @seealso [tidyr::uncount()]
#' @export
uncount <- function(data, ...) {
	result <- tidyr::uncount(data, ...)
	log_summarize(data, result, "uncount", ...)
	result
}


