# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: 
log_mutate



#' Wrapper around dplyr::mutate that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate()] that prints information about the operation.
#'
#' @inherit dplyr::mutate return
#' @inheritParams dplyr::mutate
#'
#'
#' @seealso [dplyr::mutate()]
#'
#' @export
mutate <- function(.data, ...) {
	.call <- match.call(definition = dplyr::mutate, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate)
	.call$.funname <- 'mutate'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate_all()] that prints information about the operation.
#'
#' @inherit dplyr::mutate_all return
#' @inheritParams dplyr::mutate_all
#'
#'
#' @seealso [dplyr::mutate_all()]
#'
#' @export
mutate_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::mutate_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate_all)
	.call$.funname <- 'mutate_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate_if()] that prints information about the operation.
#'
#' @inherit dplyr::mutate_if return
#' @inheritParams dplyr::mutate_if
#'
#'
#' @seealso [dplyr::mutate_if()]
#'
#' @export
mutate_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::mutate_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate_if)
	.call$.funname <- 'mutate_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::mutate_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::mutate_at()] that prints information about the operation.
#'
#' @inherit dplyr::mutate_at return
#' @inheritParams dplyr::mutate_at
#'
#'
#' @seealso [dplyr::mutate_at()]
#'
#' @export
mutate_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::mutate_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::mutate_at)
	.call$.funname <- 'mutate_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute()] that prints information about the operation.
#'
#' @inherit dplyr::transmute return
#' @inheritParams dplyr::transmute
#'
#'
#' @seealso [dplyr::transmute()]
#'
#' @export
transmute <- function(.data, ...) {
	.call <- match.call(definition = dplyr::transmute, expand.dots = TRUE)
	names(.call)[names(.call) == '.data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute)
	.call$.funname <- 'transmute'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute_all that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute_all()] that prints information about the operation.
#'
#' @inherit dplyr::transmute_all return
#' @inheritParams dplyr::transmute_all
#'
#'
#' @seealso [dplyr::transmute_all()]
#'
#' @export
transmute_all <- function(.tbl, .funs, ...) {
	.call <- match.call(definition = dplyr::transmute_all, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute_all)
	.call$.funname <- 'transmute_all'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute_if that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute_if()] that prints information about the operation.
#'
#' @inherit dplyr::transmute_if return
#' @inheritParams dplyr::transmute_if
#'
#'
#' @seealso [dplyr::transmute_if()]
#'
#' @export
transmute_if <- function(.tbl, .predicate, .funs, ...) {
	.call <- match.call(definition = dplyr::transmute_if, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute_if)
	.call$.funname <- 'transmute_if'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::transmute_at that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::transmute_at()] that prints information about the operation.
#'
#' @inherit dplyr::transmute_at return
#' @inheritParams dplyr::transmute_at
#'
#'
#' @seealso [dplyr::transmute_at()]
#'
#' @export
transmute_at <- function(.tbl, .vars, .funs, ..., .cols = NULL) {
	.call <- match.call(definition = dplyr::transmute_at, expand.dots = TRUE)
	names(.call)[names(.call) == '.tbl'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::transmute_at)
	.call$.funname <- 'transmute_at'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::add_tally that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::add_tally()] that prints information about the operation.
#'
#' @inherit dplyr::add_tally return
#' @inheritParams dplyr::add_tally
#'
#'
#' @seealso [dplyr::add_tally()]
#'
#' @export
add_tally <- function(x, wt = NULL, sort = FALSE, name = NULL) {
	.call <- match.call(definition = dplyr::add_tally, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::add_tally)
	.call$.funname <- 'add_tally'
	eval(.call, envir = parent.frame())
}


#' Wrapper around dplyr::add_count that prints information about the operation.
#'
#' @description
#' Wrapper around [dplyr::add_count()] that prints information about the operation.
#'
#' @inherit dplyr::add_count return
#' @inheritParams dplyr::add_count
#' @importFrom lifecycle deprecated
#'
#' @seealso [dplyr::add_count()]
#'
#' @export
add_count <- function(x, ..., wt = NULL, sort = FALSE, name = NULL, .drop = deprecated()) {
	.call <- match.call(definition = dplyr::add_count, expand.dots = TRUE)
	names(.call)[names(.call) == 'x'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(dplyr::add_count)
	.call$.funname <- 'add_count'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::replace_na that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::replace_na()] that prints information about the operation.
#'
#' @inherit tidyr::replace_na return
#' @inheritParams tidyr::replace_na
#'
#'
#' @seealso [tidyr::replace_na()]
#'
#' @export
replace_na <- function(data, replace, ...) {
	.call <- match.call(definition = tidyr::replace_na, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(tidyr::replace_na)
	.call$.funname <- 'replace_na'
	eval(.call, envir = parent.frame())
}


#' Wrapper around tidyr::fill that prints information about the operation.
#'
#' @description
#' Wrapper around [tidyr::fill()] that prints information about the operation.
#'
#' @inherit tidyr::fill return
#' @inheritParams tidyr::fill
#'
#'
#' @seealso [tidyr::fill()]
#'
#' @export
fill <- function(data, ..., .by = NULL, .direction = c("down", "up", "downup", "updown")) {
	.call <- match.call(definition = tidyr::fill, expand.dots = TRUE)
	names(.call)[names(.call) == 'data'] <- '.data'
	.call[[1]] <- log_mutate
	.call$.fun <- quote(tidyr::fill)
	.call$.funname <- 'fill'
	eval(.call, envir = parent.frame())
}


