# Generated by data-raw/generate_wrappers.R: do not edit by hand

# Logger category: log_mutate


#' Wrapper around dplyr::mutate that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::mutate()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::mutate
#' 
#'
#' @return See [dplyr::mutate()]
#' @seealso [dplyr::mutate()]
#' @export
mutate <- function(.data, ...) {
	result <- dplyr::mutate(.data, ...)
	log_mutate(.data, result, "mutate", ...)
	result
}



#' Wrapper around dplyr::mutate_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::mutate_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::mutate_all
#' @inheritDotParams dplyr::mutate_all
#'
#' @return See [dplyr::mutate_all()]
#' @seealso [dplyr::mutate_all()]
#' @export
mutate_all <- function(.tbl, ...) {
	result <- dplyr::mutate_all(.tbl, ...)
	log_mutate(.tbl, result, "mutate_all", ...)
	result
}



#' Wrapper around dplyr::mutate_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::mutate_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::mutate_if
#' @inheritDotParams dplyr::mutate_if
#'
#' @return See [dplyr::mutate_if()]
#' @seealso [dplyr::mutate_if()]
#' @export
mutate_if <- function(.tbl, ...) {
	result <- dplyr::mutate_if(.tbl, ...)
	log_mutate(.tbl, result, "mutate_if", ...)
	result
}



#' Wrapper around dplyr::mutate_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::mutate_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::mutate_at
#' @inheritDotParams dplyr::mutate_at
#'
#' @return See [dplyr::mutate_at()]
#' @seealso [dplyr::mutate_at()]
#' @export
mutate_at <- function(.tbl, ...) {
	result <- dplyr::mutate_at(.tbl, ...)
	log_mutate(.tbl, result, "mutate_at", ...)
	result
}



#' Wrapper around dplyr::transmute that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::transmute()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::transmute
#' 
#'
#' @return See [dplyr::transmute()]
#' @seealso [dplyr::transmute()]
#' @export
transmute <- function(.data, ...) {
	result <- dplyr::transmute(.data, ...)
	log_mutate(.data, result, "transmute", ...)
	result
}



#' Wrapper around dplyr::transmute_all that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::transmute_all()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::transmute_all
#' @inheritDotParams dplyr::transmute_all
#'
#' @return See [dplyr::transmute_all()]
#' @seealso [dplyr::transmute_all()]
#' @export
transmute_all <- function(.tbl, ...) {
	result <- dplyr::transmute_all(.tbl, ...)
	log_mutate(.tbl, result, "transmute_all", ...)
	result
}



#' Wrapper around dplyr::transmute_if that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::transmute_if()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::transmute_if
#' @inheritDotParams dplyr::transmute_if
#'
#' @return See [dplyr::transmute_if()]
#' @seealso [dplyr::transmute_if()]
#' @export
transmute_if <- function(.tbl, ...) {
	result <- dplyr::transmute_if(.tbl, ...)
	log_mutate(.tbl, result, "transmute_if", ...)
	result
}



#' Wrapper around dplyr::transmute_at that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::transmute_at()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::transmute_at
#' @inheritDotParams dplyr::transmute_at
#'
#' @return See [dplyr::transmute_at()]
#' @seealso [dplyr::transmute_at()]
#' @export
transmute_at <- function(.tbl, ...) {
	result <- dplyr::transmute_at(.tbl, ...)
	log_mutate(.tbl, result, "transmute_at", ...)
	result
}



#' Wrapper around dplyr::add_tally that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::add_tally()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::add_tally
#' @inheritDotParams dplyr::add_tally
#'
#' @return See [dplyr::add_tally()]
#' @seealso [dplyr::add_tally()]
#' @export
add_tally <- function(x, ...) {
	result <- dplyr::add_tally(x, ...)
	log_mutate(x, result, "add_tally", ...)
	result
}



#' Wrapper around dplyr::add_count that prints information about the operation
#'
#' @description
#' Wrapper around [dplyr::add_count()] that prints information about the operation.
#'
#' @details
#' Documentation generated from dplyr version 1.2.0.
#'
#' @inheritParams dplyr::add_count
#' @inheritDotParams dplyr::add_count
#'
#' @return See [dplyr::add_count()]
#' @seealso [dplyr::add_count()]
#' @export
add_count <- function(x, ...) {
	result <- dplyr::add_count(x, ...)
	log_mutate(x, result, "add_count", ...)
	result
}



#' Wrapper around tidyr::replace_na that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::replace_na()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::replace_na
#' @inheritDotParams tidyr::replace_na
#'
#' @return See [tidyr::replace_na()]
#' @seealso [tidyr::replace_na()]
#' @export
replace_na <- function(data, ...) {
	result <- tidyr::replace_na(data, ...)
	log_mutate(data, result, "replace_na", ...)
	result
}



#' Wrapper around tidyr::fill that prints information about the operation
#'
#' @description
#' Wrapper around [tidyr::fill()] that prints information about the operation.
#'
#' @details
#' Documentation generated from tidyr version 1.3.2.
#'
#' @inheritParams tidyr::fill
#' @inheritDotParams tidyr::fill
#'
#' @return See [tidyr::fill()]
#' @seealso [tidyr::fill()]
#' @export
fill <- function(data, ...) {
	result <- tidyr::fill(data, ...)
	log_mutate(data, result, "fill", ...)
	result
}


